sudo: required
language: node_js
node_js:
- "8"
services:
  - docker

before_install:
  - docker build -t aloksinghk/docker-react -f Dockerfile.dev .
scripts:
  - docker run aloksinghk/docker-react npm run test -- --coverage
deploy:
  provider: elastickbeantalk 
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-546738326534"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
